name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment variables
        env:
          PORT: ${{ vars.PORT}}
          cloud_name: ${{ vars.CLOUD_NAME }}
          api_key: ${{ secrets.API_KEY }}
          api_secret: ${{secrets.API_SECRET}}
          MONGO_URI: ${{ vars.MONGO_URI }}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          JWT_REFRESH_SECRET: ${{secrets.JWT_REFRESH_SECRET}}
        run: |
          echo "PORT=$PORT" >> $GITHUB_ENV
          echo "cloud_name=$cloud_name" >> $GITHUB_ENV
          echo "api_key=$api_key" >> $GITHUB_ENV
          echo "MONGO_URI=$MONGO_URI" >> $GITHUB_ENV
          echo "JWT_SECRET=$JWT_SECRET" >> $GITHUB_ENV
          echo "JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET" >> $GITHUB_ENV

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          # Write the multi-line private key safely
          echo "${{ secrets.SERVER_PEM }}" | tr -d '\r' > ~/.ssh/server_key.pem
          chmod 600 ~/.ssh/server_key.pem
          ssh-keyscan -H 54.158.11.160 >> ~/.ssh/known_hosts

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/server_key.pem ec2-user@13.218.39.8
            cd MARKETOS || exit
            git pull origin main
            npm install
            npm run build
            pm2 restart server || pm2 start dist/server.js --name server
          EOF
